spring:
  datasource:
    url: jdbc:mysql://localhost:3306/f2x_bank?serverTimezone=UTC
    username: f2x
    password: f2x_2024
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none